services:
  catalogdb:
    container_name: catalogdb
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catalogdb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

  basketdb:
    container_name: basketdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BasketDb
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  catalog.api:
    container_name: catalog.api
    build:
      context: .
      dockerfile: src/Catalog.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Database: "Host=ep-small-block-auhpzmpz-pooler.c-10.us-east-1.aws.neon.tech;Port=5432;Database=neondb;Username=neondb_owner;Password=npg_LbAoVEzIiW04;SSL Mode=Require;Channel Binding=Require"
    ports:
      - "8080:8080"
    depends_on:
      - catalogdb

  basket.api:
    container_name: basket.api
    build:
      context: .
      dockerfile: src/Basket/Basket.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Database: "Host=ep-autumn-frost-au29zthu-pooler.c-10.us-east-1.aws.neon.tech;Port=5432;Database=neondb;Username=neondb_owner;Password=npg_3pdRcNqa5ekJ;SSL Mode=Require;Channel Binding=Require"
      ConnectionStrings__Redis: "thriving-bit-frisky-21872.db.redis.io:15292,user=default,password=hlhklhbckFI0iuPuWRmCEwx4vINasuGG,abortConnect=false" #Redis
    ports:
      - "8081:8080"
    depends_on:
      - basketdb
      - distributedcache
