services:
  catalogdb:
    container_name: catalogdb
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catalogdb
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres_catalog:/var/lib/postgresql/data/

  basketdb:
    container_name: basketdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BasketDb
    restart: always
    ports:
      - "5434:5432"
    volumes:
      - postgres_basket:/var/lib/postgresql/data/

  distributedcache:
    container_name: distributedcache
    restart: always
    ports:
      - "6379:6379"

  catalog.api:
    container_name: catalog.api
    build:
      context: .
      dockerfile: src/Catalog.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Database: "${CATALOG_DATABASE_CONNECTION}"
    ports:
      - "8080:8080"
    depends_on:
      - catalogdb

  basket.api:
    container_name: basket.api
    build:
      context: .
      dockerfile: src/Basket/Basket.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Database: "${BASKET_DATABASE_CONNECTION}"
      ConnectionStrings__Redis: "${BASKET_REDIS_CONNECTION}"
    ports:
      - "8081:8080"
    depends_on:
      - basketdb
      - distributedcache

  orders.api:
    container_name: orders.api
    build:
      context: .
      dockerfile: src/Ordering/Orders.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      MongoDb__ConnectionString: "${MONGODB_CONNECTION_STRING}"
      MongoDb__DatabaseName: "${MONGODB_DATABASE_NAME:-OrdersDb}"
      MongoDb__CollectionName: "${MONGODB_COLLECTION_NAME:-orders}"
      Services__CatalogUrl: "https://catalogapi-gchz.onrender.com"
      Services__BasketUrl: "https://basketapi.onrender.com"
      Order__TaxRate: "0.16"
      Cors__AllowedOrigins__0: "${FRONTEND_URL:-http://localhost:5173}"
    ports:
      - "8082:8080"
