services:
  catalogdb:
    image: postgres:15
  basketdb:
    image: postgres:15
  distributedcache:
    image: redis
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
  orders.api:
    image: ${DOCKER_REGISTRY-}ordersapi

volumes:
  postgres_catalog:
  postgres_basket:
